import { FileText, CheckCircle2, ShieldAlert, Award } from 'lucide-react';

export function EvidencePanel({ candidate }) {
  if (!candidate) return null;

  const explanations = Array.isArray(candidate.explanations) ? candidate.explanations : [];

  return (
    <div className="evidence-panel-section">
      <div className="section-header">
        <FileText size={16} className="section-icon" />
        <h3 className="section-title">EVIDENCE (WHY THIS VESSEL?)</h3>
      </div>

      <div className="evidence-list">
        {explanations.length > 0 ? (
          explanations.map((exp, idx) => (
            <div key={idx} className="evidence-item">
              <CheckCircle2 size={16} className="evidence-check-icon text-success" />
              <span className="evidence-text">{exp}</span>
            </div>
          ))
        ) : (
          <p className="text-muted p-2">No evidence available</p>
        )}
      </div>

      <div className="evidence-footer">
        <div className="attribution-score-badge">
          <Award size={14} className="badge-icon" />
          <span>Source Compatibility Score: {candidate.overall_score}%</span>
        </div>

        <p className="legal-disclaimer">
          <ShieldAlert size={12} className="disclaimer-icon" />
          <span>Vessel ranking generated by multi-factor spatial, temporal and trajectory evidence scoring.</span>
        </p>
      </div>
    </div>
  );
}
