import React from 'react';
import { Target, Award, Ship, ChevronRight, BarChart3 } from 'lucide-react';
import { AttributionPanel } from '../attribution/AttributionPanel';
import { VesselSpotlightCard } from '../vessels/VesselSpotlightCard';

export function AttributionView({ candidates, selectedMmsi, onSelectCandidate, selectedCandidate }) {
  if (!candidates || candidates.length === 0) {
    return (
      <div className="trace-empty-view">
        <Target size={48} className="empty-icon text-muted" />
        <h2>No Attribution Data Available</h2>
        <p>Vessel attribution scoring engine results have not been generated by the backend server yet.</p>
      </div>
    );
  }

  return (
    <div className="view-container attribution-view-container">
      <div className="view-header">
        <div className="view-title-group">
          <Target size={22} className="view-icon text-success" />
          <div>
            <h2 className="view-title">EXPLAINABLE VESSEL ATTRIBUTION</h2>
            <span className="view-subtitle">Multi-Factor Spatial, Temporal & Trajectory Compatibility Scoring</span>
          </div>
        </div>
        <div className="top-candidate-badge">
          <Award size={16} />
          <span>Top Candidate: <strong>{candidates[0]?.vessel_name || candidates[0]?.mmsi} ({candidates[0]?.overall_score}%)</strong></span>
        </div>
      </div>

      {/* Main Grid: Selected Vessel Attribution & Candidate Ranking List */}
      <div className="view-grid-top">
        <div className="attribution-panel-column">
          <VesselSpotlightCard vessel={selectedCandidate} />
          <AttributionPanel candidate={selectedCandidate} />
        </div>

        <div className="ranking-table-column">
          <div className="ranking-card">
            <h3 className="card-section-title"><BarChart3 size={16} /> Candidate Vessel Ranking</h3>
            <div className="table-responsive">
              <table className="trace-vessel-table">
                <thead>
                  <tr>
                    <th>Rank</th>
                    <th>Vessel Identity</th>
                    <th>MMSI</th>
                    <th>Source Compatibility Score</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {candidates.map((cand, idx) => {
                    const isSelected = cand.mmsi === selectedMmsi;
                    return (
                      <tr 
                        key={cand.mmsi} 
                        className={`vessel-row ${isSelected ? 'selected' : ''}`}
                        onClick={() => onSelectCandidate(cand.mmsi)}
                      >
                        <td className="rank-col">#{idx + 1}</td>
                        <td className="font-medium">
                          <Ship size={14} className="vessel-row-icon" />
                          <span>{cand.vessel_name}</span>
                        </td>
                        <td>{cand.mmsi}</td>
                        <td className="score-col font-bold">
                          <span className="score-number">{cand.overall_score}%</span>
                        </td>
                        <td>
                          <span className={`status-pill-sm ${cand.overall_score >= 80 ? 'badge-high' : (cand.overall_score >= 50 ? 'badge-medium' : 'badge-low')}`}>
                            {cand.overall_score >= 80 ? 'Top Candidate' : (cand.overall_score >= 50 ? 'Potential Source' : 'Low Compatibility')}
                          </span>
                        </td>
                        <td>
                          <button className="select-row-btn" title="Inspect Attribution">
                            <ChevronRight size={15} />
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
