import { FileText, CheckCircle2, ShieldAlert, Award, Ship } from 'lucide-react';
import { SatelliteEvidence } from '../attribution/SatelliteEvidence';
import { VesselSpotlightCard } from '../vessels/VesselSpotlightCard';

export function EvidenceView({ incident, candidates, selectedMmsi, onSelectCandidate, selectedCandidate }) {
  if (!selectedCandidate) {
    return (
      <div className="trace-empty-view">
        <FileText size={48} className="empty-icon text-muted" />
        <h2>No Evidence Available</h2>
        <p>No candidate vessel selected or attribution evidence unavailable.</p>
      </div>
    );
  }

  const explanations = selectedCandidate.explanations && selectedCandidate.explanations.length > 0
    ? selectedCandidate.explanations
    : [];

  return (
    <div className="view-container evidence-view-container">
      <div className="view-header">
        <div className="view-title-group">
          <FileText size={22} className="view-icon text-info" />
          <div>
            <h2 className="view-title">ATTRIBUTION EVIDENCE & REASONING AUDIT</h2>
            <span className="view-subtitle">Audit Trail of Spatial, Temporal, Trajectory & AIS Behavior Evidence</span>
          </div>
        </div>
      </div>

      {/* Candidate Vessel Selector Strip */}
      <div className="vessel-selector-strip">
        <span className="strip-label">Select Candidate Vessel:</span>
        <div className="strip-buttons">
          {candidates.map((cand, idx) => (
            <button 
              key={cand.mmsi}
              className={`strip-btn ${cand.mmsi === selectedMmsi ? 'active' : ''}`}
              onClick={() => onSelectCandidate(cand.mmsi)}
            >
              <Ship size={14} />
              <span>#{idx + 1} {cand.vessel_name} ({cand.overall_score}%)</span>
            </button>
          ))}
        </div>
      </div>

      <div className="view-grid-top">
        <div className="spotlight-column">
          <VesselSpotlightCard vessel={selectedCandidate} />
          
          {/* Structured Evidence Checklist */}
          <div className="evidence-checklist-card">
            <h3 className="card-section-title"><Award size={16} /> WHY IS THIS VESSEL RANKED HIGHLY?</h3>
            <div className="checklist-items">
              <div className="check-item">
                <CheckCircle2 size={16} className="text-success" />
                <div className="check-content">
                  <strong>Spatial Compatibility:</strong> {typeof selectedCandidate.minimum_distance_km === 'number' ? `Min distance ${selectedCandidate.minimum_distance_km} km to origin.` : `Min distance unavailable.`}
                </div>
              </div>
              <div className="check-item">
                <CheckCircle2 size={16} className="text-success" />
                <div className="check-content">
                  <strong>Time Compatibility:</strong> Present during source time window ({selectedCandidate.source_window_presence === true ? 'Yes' : (selectedCandidate.source_window_presence === false ? 'No' : 'Unknown')}).
                </div>
              </div>
              <div className="check-item">
                <CheckCircle2 size={16} className="text-success" />
                <div className="check-content">
                  <strong>Trajectory Consistency:</strong> AIS track matches backward hindcast vector ({selectedCandidate.component_scores?.trajectory_consistency_score ?? 0}% score).
                </div>
              </div>
              <div className="check-item">
                <CheckCircle2 size={16} className="text-success" />
                <div className="check-content">
                  <strong>Behavioural Evidence:</strong> AIS gap detected ({selectedCandidate.ais_gap_detected === true ? 'Yes - Anomaly Recorded' : (selectedCandidate.ais_gap_detected === false ? 'No Gaps' : 'Unknown')}).
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="evidence-panel-column">
          <div className="backend-explanations-card">
            <h3 className="card-section-title"><FileText size={16} /> Backend Supporting Evidence Explanations</h3>
            {explanations.length > 0 ? (
              <div className="explanations-list">
                {explanations.map((exp, idx) => (
                  <div key={idx} className="explanation-row">
                    <CheckCircle2 size={16} className="text-success row-icon" />
                    <span>{exp}</span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-muted">No evidence available</p>
            )}

            <div className="legal-notice-box">
              <ShieldAlert size={14} className="notice-icon" />
              <span>Evidence-based ranking result generated by TRACE system logic. Not a legal conclusion.</span>
            </div>
          </div>
        </div>
      </div>

      {/* Satellite Radar Observation Pipeline */}
      <div className="view-grid-bottom">
        <SatelliteEvidence spill={incident?.spill} />
      </div>
    </div>
  );
}
